template = ""
rev_id = 4
template_sha = "87be02986858c4b7ae5e8613b6f951c3c209b221"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "sjt"
__UND2C_TRG__ = "sjd"
__UNDEFINED_SOURCE__ = "Ter Saami"
__UNDEFINED_TARGET__ = "Kildin Saami"
__UND_SRC__ = "sjt"
__UND_TRG__ = "sjd"
